config/routes.rb
Rails.application.routes.draw do
  resources :gold_balances
  resources :cash_balances
  resources :users
  resources :transactions

end

app/models/cash_balance.rb
class CashBalance < ActiveRecord::Base
  belongs_to :user
end

app/controllers/cash_balances_controller.rb
class CashBalancesController < ApplicationController
  before_action :set_cash_balance, only: [:show, :edit, :update, :destroy]

  # GET /cash_balances
  # GET /cash_balances.json
  def index
    @cash_balances = CashBalance.all
  end

  # GET /cash_balances/1
  # GET /cash_balances/1.json
  def show
  end

  # GET /cash_balances/new
  def new
    @cash_balance = CashBalance.new
  end

  # GET /cash_balances/1/edit
  def edit
  end

  # POST /cash_balances
  # POST /cash_balances.json
  def create
    @cash_balance = CashBalance.new(cash_balance_params)

    respond_to do |format|
      if @cash_balance.save
        format.html { redirect_to @cash_balance, notice: 'Cash balance was successfully created.' }
        format.json { render :show, status: :created, location: @cash_balance }
      else
        format.html { render :new }
        format.json { render json: @cash_balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cash_balances/1
  # PATCH/PUT /cash_balances/1.json
  def update
    respond_to do |format|
      if @cash_balance.update(cash_balance_params)
        format.html { redirect_to @cash_balance, notice: 'Cash balance was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash_balance }
      else
        format.html { render :edit }
        format.json { render json: @cash_balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cash_balances/1
  # DELETE /cash_balances/1.json
  def destroy
    @cash_balance.destroy
    respond_to do |format|
      format.html { redirect_to cash_balances_url, notice: 'Cash balance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash_balance
      @cash_balance = CashBalance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_balance_params
      params.require(:cash_balance).permit(:amount, :user_id)
    end
end

app/helpers/cash_balances_helper.rb
module CashBalancesHelper
end

app/views/cash_balances/_form.html.erb
<%= form_for(@cash_balance) do |f| %>
  <% if @cash_balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cash_balance.errors.count, "error") %> prohibited this cash_balance from being saved:</h2>

      <ul>
      <% @cash_balance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cash_balances/edit.html.erb
<h1>Editing Cash Balance</h1>

<%= render 'form' %>

<%= link_to 'Show', @cash_balance %> |
<%= link_to 'Back', cash_balances_path %>

app/views/cash_balances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cash Balances</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cash_balances.each do |cash_balance| %>
      <tr>
        <td><%= cash_balance.amount %></td>
        <td><%= cash_balance.user %></td>
        <td><%= link_to 'Show', cash_balance %></td>
        <td><%= link_to 'Edit', edit_cash_balance_path(cash_balance) %></td>
        <td><%= link_to 'Destroy', cash_balance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cash balance', new_cash_balance_path %>

app/views/cash_balances/new.html.erb
<h1>New Cash Balance</h1>

<%= render 'form' %>

<%= link_to 'Back', cash_balances_path %>

app/views/cash_balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @cash_balance.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @cash_balance.user %>
</p>

<%= link_to 'Edit', edit_cash_balance_path(@cash_balance) %> |
<%= link_to 'Back', cash_balances_path %>