config/routes.rb
Rails.application.routes.draw do
  resources :gold_balances
  resources :cash_balances
  resources :users
  resources :transactions

end

app/models/gold_balance.rb
class GoldBalance < ActiveRecord::Base
  belongs_to :user
end

app/controllers/gold_balances_controller.rb
class GoldBalancesController < ApplicationController
  before_action :set_gold_balance, only: [:show, :edit, :update, :destroy]

  # GET /gold_balances
  # GET /gold_balances.json
  def index
    @gold_balances = GoldBalance.all
  end

  # GET /gold_balances/1
  # GET /gold_balances/1.json
  def show
  end

  # GET /gold_balances/new
  def new
    @gold_balance = GoldBalance.new
  end

  # GET /gold_balances/1/edit
  def edit
  end

  # POST /gold_balances
  # POST /gold_balances.json
  def create
    @gold_balance = GoldBalance.new(gold_balance_params)

    respond_to do |format|
      if @gold_balance.save
        format.html { redirect_to @gold_balance, notice: 'Gold balance was successfully created.' }
        format.json { render :show, status: :created, location: @gold_balance }
      else
        format.html { render :new }
        format.json { render json: @gold_balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gold_balances/1
  # PATCH/PUT /gold_balances/1.json
  def update
    respond_to do |format|
      if @gold_balance.update(gold_balance_params)
        format.html { redirect_to @gold_balance, notice: 'Gold balance was successfully updated.' }
        format.json { render :show, status: :ok, location: @gold_balance }
      else
        format.html { render :edit }
        format.json { render json: @gold_balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gold_balances/1
  # DELETE /gold_balances/1.json
  def destroy
    @gold_balance.destroy
    respond_to do |format|
      format.html { redirect_to gold_balances_url, notice: 'Gold balance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gold_balance
      @gold_balance = GoldBalance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gold_balance_params
      params.require(:gold_balance).permit(:amount, :user_id)
    end
end

app/helpers/gold_balances_helper.rb
module GoldBalancesHelper
end

app/views/gold_balances/_form.html.erb
<%= form_for(@gold_balance) do |f| %>
  <% if @gold_balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gold_balance.errors.count, "error") %> prohibited this gold_balance from being saved:</h2>

      <ul>
      <% @gold_balance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gold_balances/edit.html.erb
<h1>Editing Gold Balance</h1>

<%= render 'form' %>

<%= link_to 'Show', @gold_balance %> |
<%= link_to 'Back', gold_balances_path %>

app/views/gold_balances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gold Balances</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gold_balances.each do |gold_balance| %>
      <tr>
        <td><%= gold_balance.amount %></td>
        <td><%= gold_balance.user %></td>
        <td><%= link_to 'Show', gold_balance %></td>
        <td><%= link_to 'Edit', edit_gold_balance_path(gold_balance) %></td>
        <td><%= link_to 'Destroy', gold_balance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gold balance', new_gold_balance_path %>

app/views/gold_balances/new.html.erb
<h1>New Gold Balance</h1>

<%= render 'form' %>

<%= link_to 'Back', gold_balances_path %>

app/views/gold_balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @gold_balance.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @gold_balance.user %>
</p>

<%= link_to 'Edit', edit_gold_balance_path(@gold_balance) %> |
<%= link_to 'Back', gold_balances_path %>